#!/bin/sh
# check if pyenv is available
# edit: fixed redirect issue in earlier version

brew_path=`which brew`

if which pyenv >/dev/null 2>&1; then
    # assumes default location of brew in `/usr/local/bin/brew`
    /usr/bin/env PATH="${PATH//$(pyenv root)\/shims:/}" ${brew_path} "$@"
else
    ${brew_path} "$@"
fi
