#!/bin/zsh

if [ $# -eq 1 ]
then
    curl -u 'bam241' https://api.github.com/user/repos -d '{"name":"'$@'"}'
    git clone git@github.com:bam241/${@}.git
    cd ${@}
    git-change-url --to-ssh
else
    if [ ! -d ".git" ]
    then
        git init
    fi
    curl -u 'bam241' https://api.github.com/user/repos -d '{"name":"'${PWD##*/}'"}'
    git remote add origin git@github.com:bam241/${PWD##*/}.git
    git-change-url --to-ssh
fi
