#!/bin/zsh



core="1"

var=""
key=""
value=""
for keyValue in "$@"
do
  case "${prefix}${keyValue}" in
    -j*)        key="-j";     value="${keyValue:2}";;
    *)                                      value=$keyValue;;
  esac
  case $key in
    -j)  core="${value}";           prefix=""; key="";;
    *)   var="${keyValue}";;
  esac
done

echo "INSTALL WITH ${core} CORES"


if [[ ${PWD##*/} =~ cyclus ]]
then
   python install.py --clean-build -j$core
elif [[ ${PWD##*/} =~ 'cycamore' ]]
then
   python install.py --clean-build -j$core
elif [[ ${PWD##*/} =~ cymetric ]]
then
    python setup.py install --prefix $(cyclus --install-path)
else
    if [ ! -f "./install.py" ]
    then
        echo "install.py missing..."
    else
        python install.py --clean-build -j$core
    fi
fi
