#!/bin/zsh



if [ $# -gt 1 ]
then
    echo "to much paramter..."
    exit(1)
fi

if [ $# -eq 1 ]
then
    in_db=${1}

else
   in_db='cyclus.sqlite'
fi

out_db=${in_db}_

cp $in_db $out_db

cyan -db $out_db flowgraph -proto | dot -Tpng > flow.png
