#!/bin/zsh


verbose="2"
out="h5"

var=""
key=""
value=""
for keyValue in "$@"
do
  case "${prefix}${keyValue}" in
    -v*)        key="-v";     value="${keyValue:2}";;
    -h5*)        key="-h5";     value="${keyValue:2}";;
    -sqlite*)        key="-sqlite";     value="${keyValue:2}";;
    *)                                      value=$keyValue;;
  esac
  case $key in
    -v)  verbose="${value}";           prefix=""; key="";;
    -h5)  out="h5";           prefix=""; key="";;
    -sqlite)  out="sqlite";           prefix=""; key="";;
    *)   var="${keyValue}";;
  esac
done

if [[ $var =~ '.xml' ]]; then
    name="${var%%.*}.${out%%.*}"
    rm $name; cyclus $var -o $name -v$verbose

else
    echo "$var is not a xml file: skeeped!"
fi    
