#!/bin/zsh


function smux
{
    if [ $# -eq 0 ]; then
        ssh hum -t `tmux attach -tmain`
    elif [ $# -gt 1 ]; then
        echo "too many parameters..."
    else
        export ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX=YES
        ssh -t hum tmux -CC attach -t$1
    fi
    unset ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX 
}
fping -t1 -c1 -o 128.104.184.177 &>/dev/null
if [ $? -eq 0 ]; then
    session_list=$(ssh hum -t -q tmux list-sessions |cut -d":" -f1 | tr '\n' ' ') 2> /dev/null 
else 
    session_list="Cyclus  DAGMC   PyNE    TechX   main"
fi
compctl -k "($session_list)"  smux
